<?php
$config['hospital']['triagelevels']=array(
        0=>array('name'=>lang('tr_level0'),'color'=>'default'),
        1=>array('name'=>lang('tr_level1'),'color'=>'label-important'),
        2=>array('name'=>lang('tr_level2'),'color'=>'label-warning'),
        3=>array('name'=>lang('tr_level3'),'color'=>'label-yelow'),
        4=>array('name'=>lang('tr_level4'),'color'=>'label-success'),
        5=>array('name'=>lang('tr_level5'),'color'=>'label-blue'),
);
$config['hospital']['roomtypes']=array(
        'room_basic'=>lang('room_basic'),
        'room_specialized'=>lang('room_specialized'),
        'room_intensive'=>lang('room_intensive'),
);